# .github/workflows/docker-publish.yml
name: Docker Build and Push

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Example: Assuming your backend Dockerfile is in 'backend/' directory
    # defaults:
    #   run:
    #     working-directory: ./backend # If Dockerfile is not in root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Alternative: Log in to GitHub Container Registry (GHCR)
      # - name: Log in to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is automatically available

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/my-backend-app
            # For GHCR: ghcr.io/${{ github.repository_owner }}/my-backend-app
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha # Git SHA as a tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend # Path to the directory containing the Dockerfile for backend
          file: ./backend/Dockerfile # Explicitly specify Dockerfile path
          push: ${{ github.event_name != 'pull_request' }} # Push only if not a PR
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Enable GitHub Actions cache for Docker layers
          cache-to: type=gha,mode=max

